@url = http://localhost:5168

### Cadastro
POST {{url}}/register
Content-Type: application/json

{ "email": "ana@teste.com", "password": "Senh@1234", "nomeCompleto": "Ana teste" }

### Login (devolve um token)
POST {{url}}/login
Content-Type: application/json

{ "email": "ana@teste.com", "password": "Senha1234" }

### Rota protegida (cole o accessToken do login)
GET {{url}}/eu
Authorization: Bearer COLE_O_TOKEN_AQUI